easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Teclado
        - App\Entity\Categoria
        - App\Entity\Usuario
        - App\Entity\TecladoUsuario
