<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZCbsdrP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZCbsdrP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZCbsdrP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZCbsdrP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZCbsdrP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZCbsdrP',
    'container.build_id' => '386f9859',
    'container.build_time' => 1614342846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZCbsdrP');
